### ISSUE TITLE
Make extension jpm compatible

### ISSUE THREAD

**Issue by SebastianZ** [a2sheppy/mdn-save-with-comment#5]
cfx for packaging and running add-ons got replaced by jpm. To get the extension to work with jpm, its package.json needs to be adjusted.

jpm requires the package.json to contain:
1. a proper `id`.
2. a `main` property as entry point.

Sebastian

**Comment by a2sheppy** [comment]
This is no longer relevant since the extension needs to be converted into a WebExtension.
